# Generated by Django 3.2.8 on 2021-10-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app4', '0002_remove_channel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='topic_url',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
